name: Run Tests

on: push

jobs:

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: goweb_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.23.x'

    - name: Install dependencies
      run: go mod download

    - name: Test
      env:
        APP_ENV: test
        ROOT_DIR: /home/runner/work/go-web/go-web
        DB_HOST: localhost
      run: |
        go test -v ./tests
